global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

scrape_configs:

  # ========================
  # GATEWAY
  # ========================
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:8080'] # [prod] 10.1.0.196:8080


  # ========================
  # ACCOUNT SERVICE
  # ========================
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8201'] # [prod] 10.1.0.195:8201


  # ========================
  # DISPATCH SERVICE
  # ========================
  - job_name: 'dispatch-service'
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8202'] # [prod] 10.2.0.160:8202



  # ========================
  # TRIP SERVICE
  # ========================
  - job_name: 'trip-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8203'] # [prod] 10.2.0.26:8203


  # ========================
  # PAYMENT SERVICE
  # ========================
  - job_name: 'payment-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8204'] # [prod] 10.2.0.69:8204


  # ========================
  # SUPPORT SERVICE
  # ========================
  - job_name: 'support-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8205'] # [prod] 10.1.0.70:8205


  # ========================
  # Redis Monitoring
  # ========================
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121'] # [prod] 10.2.0.28:9121 또는 redis-exporter:9121

