spring:
  config:
    import:
      - secrets.yml

server:
  port: ${service.port}

eureka:
#  instance:
#    hostname: GD-EUREKA                    # 도커 컨테이너명과 일치시킴 | 로컬 실행의 경우, localhost
  client:
    register-with-eureka: false
    fetch-registry: false
#    service-url:                          # 내가 접속할 Eureka Server 주소 지정. 복수 Eureka 서버일 경우 주석 해제
#      defaultZone: http://server:${service.port}/eureka/
